# Config for macthing Japan assets

gcp_project: tz-data-dev

current_mappings: japan/matches/kitamoto_gem_validated_matches_hash.csv
comparison_xml: japan/duke_configs/Comparison_kitamoto_gem.xml
deduplication_xml: japan/duke_configs/Deleteduplicates_kitamoto_gem.xml


# ---- settings ----
aggregated_units: false
clean_name_before_aggregation: false
country_wise: false

parallel_duke_processes: false
process_limit: 4
# ---------------------------------------------------------------------------- #
#                                  Data Source Config                          #
# ---------------------------------------------------------------------------- #

KITAMOTOGEM:
  bq_table: japan.kitamoto_power_assets
  aggregate_units: true
  clean_name: false
  remove_matched_data: true
  reliability_score: 5
  technology_map:
    biomass: biomass
    solar: solar
    hydro: hydropower
    pumped_hydro: hydropower
    thermal: thermal
    wind: onshore_wind
    geothermal: geothermal
    nuclear: nuclear
GEM:
  bq_table: tz_assets.power_assets_temp
  aggregate_units: true
  clean_name: false
  remove_matched_data: true
  reliability_score: 5
  technology_map:
    gas-turbine: thermal
    combined-cycle: thermal
    oil-unspecified: thermal
    coal-unspecified: thermal
    gas-oil-cofiring: thermal
    open-cycle-gas-turbine: thermal
    gas-unspecified: thermal
    steam-turbine: thermal
    petroleum-products-internal-combustion-engine: thermal
    subcritical: thermal
    supercritical: thermal
    coal-bio-cofiring: thermal
    gas-coal-cofiring: thermal
    ultrasupercritical: thermal
    internal-combustion-combined-cycle: thermal
    integrated-gasification-combined-cycle: thermal
    cofiring-unspecified: thermal
    gas-ccs: thermal
    coal-ccs: thermal
    gas-bio-cofiring: thermal
    coal-cogeneration: thermal
    thermal-unspecified: thermal
    waste: thermal # added this extra
    biogas: biomass
    biomass: biomass
    bioenergy-unspecified: biomass
    bioenergy: biomass
    hydro-unspecified: hydropower
    hydro-reservoir: hydropower
    hydro-pumped-storage: hydropower
    hydro-run-of-river: hydropower
    hydro-reservoir-and-run-of-river: hydropower
    hydro-reservoir-and-pumped-storage: hydropower
    geothermal-unspecified: geothermal
    geothermal-flash-steam: geothermal
    geothermal-flash-steam-unspecified: geothermal
    geothermal-flash-steam-single: geothermal
    geothermal-flash-steam-double: geothermal
    geothermal-flash-steam-triple: geothermal
    geothermal-dry-steam: geothermal
    geothermal-binary-cycle: geothermal
    enhanced-geothermal-system: geothermal
    geothermal: geothermal


target_operating_status:
  - operating
  - committed
  - planned
  - inactive


target_technologies:
  - thermal
  - biomass
  - hydropower
  - geothermal

target_columns:
  - Name
  - Technology
  - Capacity
  - lat
  - lon
  - admin_1
  - projectID


target_admin_1s:
- 'JPN-AI'
- 'JPN-AK'
- 'JPN-AO'
- 'JPN-CH'
- 'JPN-EH'
- 'JPN-FI'
- 'JPN-FO'
- 'JPN-FS'
- 'JPN-GF'
- 'JPN-GM'
- 'JPN-HG'
- 'JPN-HK'
- 'JPN-HS'
- 'JPN-IB'
- 'JPN-IS'
- 'JPN-IW'
- 'JPN-KC'
- 'JPN-KG'
- 'JPN-KM'
- 'JPN-KN'
- 'JPN-KS'
- 'JPN-KY'
- 'JPN-ME'
- 'JPN-MG'
- 'JPN-MZ'
- 'JPN-NI'
- 'JPN-NN'
- 'JPN-NR'
- 'JPN-NS'
- 'JPN-ON'
- 'JPN-OS'
- 'JPN-OT'
- 'JPN-OY'
- 'JPN-SG'
- 'JPN-SH'
- 'JPN-SM'
- 'JPN-ST'
- 'JPN-SZ'
- 'JPN-TC'
- 'JPN-TK'
- 'JPN-TS'
- 'JPN-TT'
- 'JPN-TY'
- 'JPN-WK'
- 'JPN-YC'
- 'JPN-YN'
- 'JPN-YT'


# ---------------------------------------------------------------------------- #
#                                Matching Config                               #
# ---------------------------------------------------------------------------- #

# matching_sources, only the matched powerplants are added to the final dataset
matching_sources:
  # Make individual queries for the datasets as done in `fully_included_sources`
  # Queries are combined with `main_query` with an `and` operator
  - KITAMOTOGEM
  - GEM

# # fully_included_sources, these sources are included even without match to the final dataset
fully_included_sources:
  - KITAMOTOGEM
  - GEM

hash: "matchingjapankitgem"


# ---------------------------------------------------------------------------- #
#                             Data Structure Config                            #
# ---------------------------------------------------------------------------- #

target_countries:
  - JPN
target_fueltypes:
  []

clean_name:
  remove_common_words: false # remove words which appear more that 20 times in all entries
  remove_duplicated_words: false
  replace:
    " ": "[^a-zA-Z]" # non-alphabetical symbols
    "":
      # This should be a list, if remove_common_words is true.
      [power, ltd, co, limited]
      # [
      #   # \w, #remove single letters
      # ]
