# Config for macthing Japan assets

gcp_project: tz-data-dev

current_mappings: japan/matches/all_four_example.csv
comparison_xml: japan/duke_configs/Comparison_all_four_sources.xml
deduplication_xml: japan/duke_configs/Deleteduplicates_units.xml
# ---------------------------------------------------------------------------- #
#                                  Data Soursce Config                          #
# ---------------------------------------------------------------------------- #


KITAMOTO:
  bq_table: japan.kitamoto_power_assets
  aggregate_units: false
  clean_name: true
  remove_matched_data: true
  reliability_score: 5
  technology_map:
    biomass: biomass
    solar: solar
    hydro: hydropower
    pumped_hydro: hydropower
    thermal: thermal
    wind: onshore_wind
    geothermal: geothermal
    nuclear: nuclear
FIT:
  bq_table: japan.fit_portal_above_20kw
  aggregate_units: false
  clean_name: true
  remove_matched_data: true
  reliability_score: 5
  technology_map:
    biomass: biomass
    solar: solar
    onshore_wind: onshore_wind
    offshore_wind: offshore_wind
    hydropower: hydropower
    geothermal: geothermal
    other: other
HJKS:
  bq_table: japan.hjks_power_units
  aggregate_units: false
  clean_name: true
  remove_matched_data: true
  reliability_score: 5
  technology_map:
    hydro: hydropower
    other: other
    nuclear: nuclear
    thermal (gas): thermal
    thermal (coal): thermal
    thermal (oil): thermal
    unknown: unknown
GEM:
  bq_table: tz_assets.power_assets_temp
  aggregate_units: false
  clean_name: false
  remove_matched_data: true
  reliability_score: 5
  technology_map:
    gas-turbine: thermal
    combined-cycle: thermal
    oil-unspecified: thermal
    coal-unspecified: thermal
    gas-oil-cofiring: thermal
    open-cycle-gas-turbine: thermal
    gas-unspecified: thermal
    steam-turbine: thermal
    petroleum-products-internal-combustion-engine: thermal
    subcritical: thermal
    supercritical: thermal
    coal-bio-cofiring: thermal
    gas-coal-cofiring: thermal
    ultrasupercritical: thermal
    internal-combustion-combined-cycle: thermal
    integrated-gasification-combined-cycle: thermal
    cofiring-unspecified: thermal
    gas-ccs: thermal
    coal-ccs: thermal
    gas-bio-cofiring: thermal
    coal-cogeneration: thermal
    thermal-unspecified: thermal
    waste: thermal # added this extra
    biogas: biomass
    biomass: biomass
    bioenergy-unspecified: biomass
    bioenergy: biomass
    hydro-unspecified: hydropower
    hydro-reservoir: hydropower
    hydro-pumped-storage: hydropower
    hydro-run-of-river: hydropower
    hydro-reservoir-and-run-of-river: hydropower
    hydro-reservoir-and-pumped-storage: hydropower

target_technologies:
  - biomass
  - thermal
  - hydropower
  - unknown
  - geothermal

target_columns:
  - Name
  - owner
  # - unit_name
  # - unit_number
  - Technology
  - Capacity
  - lat
  - lon
  - grid_region
  - admin_1
  # - start_date
  # - retire_date
  - projectID

target_gem_operating_status:
  - operating
  - committed
  - planned
  - inactive

only_operating_fit_projects: false

target_grid_regions:
  - Hokkaido
  - Tohoku
  - Hokuriku
  - Chubu
  - Kansai
  - Chugoku
  - Shikoku
  - Kyushu
  - Okinawa
  - Tokyo

target_admin_1s:
- 'JPN-AI'
- 'JPN-AK'
# - 'JPN-AO'
# - 'JPN-CH'
# - 'JPN-EH'
# - 'JPN-FI'
# - 'JPN-FO'
# - 'JPN-FS'
# - 'JPN-GF'
# - 'JPN-GM'
# - 'JPN-HG'
# - 'JPN-HK'
# - 'JPN-HS'
# - 'JPN-IB'
# - 'JPN-IS'
# - 'JPN-IW'
# - 'JPN-KC'
# - 'JPN-KG'
# - 'JPN-KM'
# - 'JPN-KN'
# - 'JPN-KS'
# - 'JPN-KY'
# - 'JPN-ME'
# - 'JPN-MG'
# - 'JPN-MZ'
# - 'JPN-NI'
# - 'JPN-NN'
# - 'JPN-NR'
# - 'JPN-NS'
# - 'JPN-ON'
# - 'JPN-OS'
# - 'JPN-OT'
# - 'JPN-OY'
# - 'JPN-SG'
# - 'JPN-SH'
# - 'JPN-SM'
# - 'JPN-ST'
# - 'JPN-SZ'
# - 'JPN-TC'
# - 'JPN-TK'
# - 'JPN-TS'
# - 'JPN-TT'
# - 'JPN-TY'
# - 'JPN-WK'
# - 'JPN-YC'
# - 'JPN-YN'
# - 'JPN-YT'

# ---------------------------------------------------------------------------- #
#                                Matching Config                               #
# ---------------------------------------------------------------------------- #

# matching_sources, only the matched powerplants are added to the final dataset
matching_sources:
  # Make individual queries for the datasets as done in `fully_included_sources`
  # Queries are combined with `main_query` with an `and` operator
  - KITAMOTO
  - FIT
  - GEM
  - HJKS

# # fully_included_sources, these sources are included even without match to the final dataset
fully_included_sources:
  - KITAMOTO
  - FIT
  - GEM
  - HJKS

hash: "matchingjapanunits3"


# ---- settings ----
country_wise: false

parallel_duke_processes: false
process_limit: 4


# ---------------------------------------------------------------------------- #
#                             Data Structure Config                            #
# ---------------------------------------------------------------------------- #

target_countries:
  - JPN
target_fueltypes:
  []

clean_name:
  remove_common_words: false # remove words which appear more that 20 times in all entries
  remove_duplicated_words: false
  replace:
    " ": "[^a-zA-Z]" # non-alphabetical symbols
    "":
      # This should be a list, if remove_common_words is true.
      [power, ltd, co, limited, plant, station]
      # [
      #   # \w, #remove single letters
      # ]
